name: Kiro Auto Bot - TikTok to YouTube

on:
  schedule:
    - cron: '0 */5 * * *' # يعمل كل 5 ساعات
  workflow_dispatch: # للتشغيل اليدوي

jobs:
  run-automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install System Tools (FFmpeg, Python, & yt-dlp)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          # تثبيت المكتبة السحرية لتخطي حماية تيك توك
          pip3 install curl_cffi 
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Install Node Modules
        run: npm install googleapis

      - name: Run Kiro Bot
        run: node index.js

      - name: Save and Push History
        run: |
          git config --global user.name "Kiro Bot"
          git config --global user.email "bot@kirozozo.com"
          git add history.json
          git commit -m "Update history.json [skip ci]" || echo "No changes to commit"
          git push
